

POST http://localhost:3003/user 
Content-Type: application/json

{
    "name": "Amanda", "email": "amanda@email.coma", "password": "123456"

}

###

POST http://localhost:3003/movie 
Content-Type: application/json

{
    "title": "testando", "description": "testando filme.", "durationInMinutes": 184, "yearOfRelease": 1993

}
